### PR TITLE
Adds options to send only on failure or send only failed tests.

### PR DESCRIPTION
**Pull request by scottfalkingham**
To not be bombarded by slack messages, an option to send to slack only if the tests failed was added along with another option to send only the failed tests.

### CODE REVIEW

**Comment by ngs** [comment]
Thanks!

**Comment by michaeltroger** [comment]
@ngs could you update it on the npm repository? There this useful feature is still not included.

**Comment by tlaukkanen** [comment]
@ngs I agree with @michaeltroger that it would be great to have new published version of this (e.g. 0.0.3) so that we could limit the Slack update to include only the failures. Or would you be willing to add some new owner to npm who could do the publishing there?

**Comment by aamorozov** [comment]
@ngs Could you please update the npm repo with this updates ?

**Pull request merged**
